# -*- coding: utf-8 -*-
"""Taller de diccionarios y listas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lsSwX85hlP7EL8czdvTYi7pAMN0Q12k5

TALLER DE LISTAS Y DICCIONARIOS

HECHO POR: Santiago Yucuma Rodriguez
"""

#Ejercicio 1

nombres = [ "Juan", "Ana", "Luis", "Pedro"]
print(*nombres)

nombres[3]="Carlos"
print(*nombres)

nombres.append("Lucia")
print(*nombres)

nombres.pop(0)
print(*nombres)

print(len(nombres))

#Ejercicio 2

edades = {
    "Juan": 25,
    "Ana": 30,
    "Luis": 28,
}

print(edades)

print("La edad de Ana es: ", edades["Ana"])

edades ["Luis"]=29
print(edades)

edades ["Pedro"]=22
print(edades)

del edades["Juan"]
print(edades)

print("La cantidad de personas es: ", len(edades))

print("Tabla actualizada con edades : ", (edades))

#Ejercico 3

libros = {
    "Cien Años de Soledad": {
        "autor": "Gabriel Garcia Marquez",
        "Año": 1967,
        "genero": "Realismo Magico"
    },
    "Don Quijote de la Mancha": {
        "autor": "Miguel de Cervantes",
        "Año": 1605,
        "genero": "Novela"
    },

}

print(libros)

print("El autor de Don Quijote de la Mancha es: ", libros["Don Quijote de la Mancha"]["autor"])

libros ["Fahrenheit 451"]= {
    "autor": "Ray Bradbury",
    "Año": 1953,
    "genero": "Ciencia Ficcion"
}
print(libros)

libros["Cien Años de Soledad"]["Año"]=1953
print("La fecha ha sido modificada con exito a: ", libros["Cien Años de Soledad"]["Año"])

print("El numero total de libros es de:")

for i, libro in enumerate(libros, start=1):
    print(f"{i}. {libro}")

#Ejercicio 4

colores=["Rojo", "Verde", "Azul", "Amarillo"]
print("Los colores de tu lista son: ")

for i, color in enumerate(colores):
    print(f"{i+1}. {color}")

colores[0]="Naranja"
print("Los colores de tu lista se han actualizado: ")

for i, color in enumerate(colores):
    print(f"{i+1}. {color}")

colores.pop()
print("Los colores de tu lista se han actualizado: ")

for i, color in enumerate(colores):
    print(f"{i+1}. {color}")

print("Los colores de tu lista son: ")

for i, color in enumerate(colores):
    print(f"{i+1}. {color}")

print("La cantidad de colores es de: ", len(colores))

#Ejercicio 5

inventario = {
    "Manzanas": [100, 150, 200],
    "Naranjas": [50, 80, 120],
    "Peras": [75, 60, 90],
    "Platanos": [40, 30, 50]
}

print("El inventario de Manzanas es: ")

for i, manzana in enumerate(inventario["Manzanas"]):
    print(f"{i+1}. Manzanas: {manzana}")

print("El inventario de Naranjas es: ")

for i, naranja in enumerate(inventario["Naranjas"]):
    print(f"{i+1}. Naranjas: {naranja}")

print("El inventario de Peras es: ")

for i, pera in enumerate(inventario["Peras"]):
    print(f"{i+1}. Peras: {pera}")

print("El inventario de Platanos es: ")

for i, platano in enumerate(inventario["Platanos"]):
    print(f"{i+1}. Platanos: {platano}")

print ("El inventario total es de: ")

for i, inven in enumerate(inventario):
    print(f"{i+1}. {inven}")